server:
  port: 8080

encoding: UTF-8
token-url: https://oauth.battle.net/token

client-info:
  client_id: cfedb28e025647c2b92ffce701f2f6fb
  client_secret: r6di890DROLdDe1obUHR49xRJgFdEv7e

logging:
  level:
    org:
      springframework:
        security: debug

spring:
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    generate-ddl: auto
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true

  datasource:
    auth:
      url: jdbc:postgresql://localhost:5432/GuessHearthAuth
      username: postgres
      password: Z@h@R952
    cards:
      url: jdbc:postgresql://localhost:5432/Cards
      username: postgres
      password: Z@h@R952