server:
  port: 8080

encoding: UTF-8
token-url: https://oauth.battle.net/token

client-info:
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}

logging:
  level:
    org:
      springframework:
        security: debug

spring:
  config:
    import: env.properties

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    generate-ddl: auto
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true

  datasource:
    auth:
      url: ${AUTH_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    cards:
      url: ${CARDS_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
