server:
  port: 8080
  ssl:
    key-store: classpath:keystore/keystore.jks
    key-store-password: zpatrV
    key-password: zpatrV
    keyStoreType: PKCS12
    key-alias: GuessHearthApp
    enabled: true

encoding: UTF-8
token-url: https://oauth.battle.net/token

client-info:
  client_id: cfedb28e025647c2b92ffce701f2f6fb
  client_secret: r6di890DROLdDe1obUHR49xRJgFdEv7e

logging:
  level:
    org:
      springframework:
        security: trace

spring:
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    generate-ddl: auto
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/GuessHearthAuth
    username: postgres
    password: Z@h@R952